version: "3.7"

services:
    api:
        build: .
        image: api
        container_name: api
        ports:
            - 5000:5000
        command: flask run -h 0.0.0.0
        environment: 
            - FLASK_APP=manage:app
            - FLASK_ENV=development
            - APP_SETTINGS=server.config_profiles.DevConfig
            - PYTHONDONTWRITEBYTECODE=1
            - PYTHONUNBUFFERED=1
        volumes:
            - .:/usr/src/app

    worker:
        image: api
        command: python manage.py start_worker
        volumes:
            - .:/usr/src/app
        environment: 
            - APP_SETTINGS=server.config_profiles.DevConfig
        depends_on:
            - redis

    scheduler:
        image: api
        command: rqscheduler --host redis --port 6379 --db 0
        volumes:
            - .:/usr/src/app
        environment: 
            - APP_SETTINGS=server.config_profiles.DevConfig
        depends_on: 
            - worker

    redis:
        image: redis:5.0.7-alpine